<?php
/* based on ORSCF VisitData Contract v1.9.1.11852 */


public class UidValueCriteria {
  
  /*
  * The value to match.
  */
  public string $value;
  
}

public class StringValueCriteria {
  
  /*
  * The value to match.
  */
  public string $value;
  
  /*
  * Enables, that the given value can just be a substring within the content of the target field. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $matchSubstring;
  
}

/*
* Declares, how the corresponding 'value' should be compared. DEFAULT (if this is undefined or null) is 'Equal'(1).
*/
public interface RangeMatchingBehaviour extends Enum {
  
}

public class DateValueCriteria {
  
  /*
  * The value to match.
  */
  public string $value;
  
  /*
  * Declares, how the corresponding 'value' should be compared. DEFAULT (if this is undefined or null) is 'Equal'(1).
  */
  public RangeMatchingBehaviour $matchingBehaviour;
  
}

public class VisitMetaRecord {
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $visitUid;
  
  public string $studyUid;
  
  public string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

/*
* Declares, which portion of the corresponding 'value' should be compared. DEFAULT (if this is undefined or null) is 'Date'(3).
*/
public interface DataEnrollmentValidationState extends Enum {
  
}

public class DataRecordingMetaRecord {
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $dataRecordingUid;
  
  public string $visitUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class CustomFieldDescriptor {
  
  public string $technicalName;
  
  public bool $isRequired;
  
  public string $displayLabel;
  
  public string $inputDescription;
  
  public string $defaultValue;
  
  public array $presets;
  
  public bool $presetsOnly;
  
  public string $regularExpression;
  
}

public class VisitFields implements VisitMetaRecord {
  
  /*
  * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitProcedureName;
  
  /*
  * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitExecutionTitle;
  
  /*
  * the estimated date when the visit is scheduled for execution *this field is optional
  */
  public ?string $scheduledDateUtc;
  
  /*
  * the real date, when the visits was executed *this field is optional
  */
  public ?string $executionDateUtc;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public int $executionState;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $visitUid;
  
  public string $studyUid;
  
  public string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

/*
* A structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
*/
public class VisitFhirRessourceContainer implements VisitMetaRecord {
  
  /*
  * a HL7 <see href="http://www.hl7.org/fhir/appointment.html">'Appointment'</see> resource in json format
  */
  public object $appointmentRessource;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $visitUid;
  
  public string $studyUid;
  
  public string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class BatchableVisitMutation {
  
  /*
  * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitProcedureName;
  
  /*
  * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitExecutionTitle;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public ?int $executionState;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
}

public class UidFieldFilter {
  
  /*
  * Specifies one or more values to match. DEFAULT (if this is undefined or null) will include everything (but NULL) to enable filtering based on 'excluded values'. An empty array which just has no elements will be treaded as valid input and results in no value matching, so this only makes sense when including NULL instead (if supported). An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $includedValues;
  
  /*
  * Specifies one or more values to be removed from the result set which was evaulated using the 'included values'. DEFAULT (if this is undefined or null) will just leave the filtering based on 'included values'. An empty array which just has no elements will also be ignored. An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $excludedValues;
  
  /*
  * Negates the outcome of the whole filter. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $negate;
  
}

public class StringFieldFilter {
  
  /*
  * Specifies one or more values to match. DEFAULT (if this is undefined or null) will include everything (but NULL) to enable filtering based on 'excluded values'. An empty array which just has no elements will be treaded as valid input and results in no value matching, so this only makes sense when including NULL instead (if supported). An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $includedValues;
  
  /*
  * Specifies one or more values to be removed from the result set which was evaulated using the 'included values'. DEFAULT (if this is undefined or null) will just leave the filtering based on 'included values'. An empty array which just has no elements will also be ignored. An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $excludedValues;
  
  /*
  * Enables, that the included and excluded values are processed case-insenstive. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $ignoreCasing;
  
  /*
  * Negates the outcome of the whole filter. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $negate;
  
}

public class IntegerValueCriteria {
  
  /*
  * The value to match.
  */
  public int $value;
  
  /*
  * Declares, how the corresponding 'value' should be compared. DEFAULT (if this is undefined or null) is 'Equal'(1).
  */
  public RangeMatchingBehaviour $matchingBehaviour;
  
}

public class DateFieldFilter {
  
  /*
  * Specifies one or more values to match. DEFAULT (if this is undefined or null) will include everything (but NULL) to enable filtering based on 'excluded values'. An empty array which just has no elements will be treaded as valid input and results in no value matching, so this only makes sense when including NULL instead (if supported). An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $includedValues;
  
  /*
  * Specifies one or more values to be removed from the result set which was evaulated using the 'included values'. DEFAULT (if this is undefined or null) will just leave the filtering based on 'included values'. An empty array which just has no elements will also be ignored. An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $excludedValues;
  
  /*
  * Negates the outcome of the whole filter. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $negate;
  
}

public class DataRecordingFields implements DataRecordingMetaRecord {
  
  /*
  * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $dataRecordingName;
  
  /*
  * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $taskExecutionTitle;
  
  /*
  * the estimated date when the visit is scheduled *this field is optional
  */
  public ?string $scheduledDateTimeUtc;
  
  /*
  * the real time, when the data was recorded *this field is optional
  */
  public ?string $executionDateTimeUtc;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public int $executionState;
  
  /*
  * schema-url of the data which were stored inside of the 'RecordedData' field
  */
  public string $dataSchemaUrl;
  
  /*
  * version of schema, which is addressed by the 'DataSchemaUrl'
  */
  public string $dataSchemaVersion;
  
  /*
  * 'FhirQuestionaire' / 'XML' / 'CSV' / 'Custom'
  */
  public string $dataSchemaKind;
  
  /*
  * Language of free-text information inside of the data content
  */
  public string $dataLanguage;
  
  /*
  * additional notes regarding this dedcated execution (supplied by the execution person) *this field is optional (use null as value)
  */
  public string $notesRegardingOutcome;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $dataRecordingUid;
  
  public string $visitUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class IntegerFieldFilter {
  
  /*
  * Specifies one or more values to match. DEFAULT (if this is undefined or null) will include everything (but NULL) to enable filtering based on 'excluded values'. An empty array which just has no elements will be treaded as valid input and results in no value matching, so this only makes sense when including NULL instead (if supported). An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $includedValues;
  
  /*
  * Specifies one or more values to be removed from the result set which was evaulated using the 'included values'. DEFAULT (if this is undefined or null) will just leave the filtering based on 'included values'. An empty array which just has no elements will also be ignored. An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $excludedValues;
  
  /*
  * Negates the outcome of the whole filter. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $negate;
  
}

public class DataRecordingStructure implements DataRecordingFields {
  
  /*
  * RAW data, in the schema as defined at the 'DataSchemaUrl'
  */
  public string $recordedData;
  
  /*
  * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $dataRecordingName;
  
  /*
  * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $taskExecutionTitle;
  
  /*
  * the estimated date when the visit is scheduled *this field is optional
  */
  public ?string $scheduledDateTimeUtc;
  
  /*
  * the real time, when the data was recorded *this field is optional
  */
  public ?string $executionDateTimeUtc;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public int $executionState;
  
  /*
  * schema-url of the data which were stored inside of the 'RecordedData' field
  */
  public string $dataSchemaUrl;
  
  /*
  * version of schema, which is addressed by the 'DataSchemaUrl'
  */
  public string $dataSchemaVersion;
  
  /*
  * 'FhirQuestionaire' / 'XML' / 'CSV' / 'Custom'
  */
  public string $dataSchemaKind;
  
  /*
  * Language of free-text information inside of the data content
  */
  public string $dataLanguage;
  
  /*
  * additional notes regarding this dedcated execution (supplied by the execution person) *this field is optional (use null as value)
  */
  public string $notesRegardingOutcome;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $dataRecordingUid;
  
  public string $visitUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class VisitStructure implements VisitFields {
  
  public array $dataRecordings;
  
  /*
  * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitProcedureName;
  
  /*
  * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitExecutionTitle;
  
  /*
  * the estimated date when the visit is scheduled for execution *this field is optional
  */
  public ?string $scheduledDateUtc;
  
  /*
  * the real date, when the visits was executed *this field is optional
  */
  public ?string $executionDateUtc;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public int $executionState;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $visitUid;
  
  public string $studyUid;
  
  public string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class VisitFilter {
  
  public UidFieldFilter $studyUid;
  
  public UidFieldFilter $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public StringFieldFilter $subjectIdentifier;
  
  public StringFieldFilter $visitProcedureName;
  
  /*
  * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public StringFieldFilter $visitExecutionTitle;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public IntegerFieldFilter $executionState;
  
  public DateFieldFilter $scheduledDateUtc;
  
  public DateFieldFilter $executionDateUtc;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
}
