<?php
/* based on ORSCF VisitData Contract v1.7.0.0 */


public class VisitFilter {
  
  public ?string $studyUid;
  
  public ?string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $visitProcedureName;
  
  /*
  * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitExecutionTitle;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public ?int $executionState;
  
  public ?string $minScheduledDateUtc;
  
  public ?string $maxScheduledDateUtc;
  
  public ?string $minExecutionDateUtc;
  
  public ?string $maxExecutionDateUtc;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
}

public class VisitMetaRecord {
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $visitUid;
  
  public string $studyUid;
  
  public string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class DataRecordingMetaRecord {
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $dataRecordingUid;
  
  public string $visitUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class CustomFieldDescriptor {
  
  public string $technicalName;
  
  public bool $isRequired;
  
  public string $displayLabel;
  
  public string $inputDescription;
  
  public string $defaultValue;
  
  public array $presets;
  
  public bool $presetsOnly;
  
  public string $regularExpression;
  
}

public class VisitFields implements VisitMetaRecord {
  
  /*
  * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitProcedureName;
  
  /*
  * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitExecutionTitle;
  
  /*
  * the estimated date when the visit is scheduled for execution *this field is optional
  */
  public ?string $scheduledDateUtc;
  
  /*
  * the real date, when the visits was executed *this field is optional
  */
  public ?string $executionDateUtc;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public int $executionState;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $visitUid;
  
  public string $studyUid;
  
  public string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

/*
* A structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
*/
public class VisitFhirRessourceContainer implements VisitMetaRecord {
  
  /*
  * a HL7 <see href="http://www.hl7.org/fhir/appointment.html">'Appointment'</see> resource in json format
  */
  public object $appointmentRessource;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $visitUid;
  
  public string $studyUid;
  
  public string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class BatchableVisitMutation {
  
  /*
  * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitProcedureName;
  
  /*
  * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitExecutionTitle;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public ?int $executionState;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
}

public class DataRecordingFields implements DataRecordingMetaRecord {
  
  /*
  * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $dataRecordingName;
  
  /*
  * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $taskExecutionTitle;
  
  /*
  * the estimated date when the visit is scheduled *this field is optional
  */
  public ?string $scheduledDateTimeUtc;
  
  /*
  * the real time, when the data was recorded *this field is optional
  */
  public ?string $executionDateTimeUtc;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public int $executionState;
  
  /*
  * schema-url of the data which were stored inside of the 'RecordedData' field
  */
  public string $dataSchemaUrl;
  
  /*
  * additional notes regarding this dedcated execution (supplied by the execution person) *this field is optional (use null as value)
  */
  public string $notesRegardingOutcome;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $dataRecordingUid;
  
  public string $visitUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class DataRecordingStructure implements DataRecordingFields {
  
  /*
  * RAW data, in the schema as defined at the 'DataSchemaUrl'
  */
  public string $recordedData;
  
  /*
  * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $dataRecordingName;
  
  /*
  * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $taskExecutionTitle;
  
  /*
  * the estimated date when the visit is scheduled *this field is optional
  */
  public ?string $scheduledDateTimeUtc;
  
  /*
  * the real time, when the data was recorded *this field is optional
  */
  public ?string $executionDateTimeUtc;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public int $executionState;
  
  /*
  * schema-url of the data which were stored inside of the 'RecordedData' field
  */
  public string $dataSchemaUrl;
  
  /*
  * additional notes regarding this dedcated execution (supplied by the execution person) *this field is optional (use null as value)
  */
  public string $notesRegardingOutcome;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $dataRecordingUid;
  
  public string $visitUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class VisitStructure implements VisitFields {
  
  public array $dataRecordings;
  
  /*
  * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitProcedureName;
  
  /*
  * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
  */
  public string $visitExecutionTitle;
  
  /*
  * the estimated date when the visit is scheduled for execution *this field is optional
  */
  public ?string $scheduledDateUtc;
  
  /*
  * the real date, when the visits was executed *this field is optional
  */
  public ?string $executionDateUtc;
  
  /*
  * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
  */
  public int $executionState;
  
  /*
  * *this field is optional (use null as value)
  */
  public string $executingPerson;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $visitUid;
  
  public string $studyUid;
  
  public string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}
