
".\kGen\kGEN.exe" "generate-interfaces.BDR.json" > "..\Contracts\BDR-Contract\v1\interfaces.php"
".\kGen\kGEN.exe" "generate-interfaces.IMS.json" > "..\Contracts\IMS-Contract\v1\interfaces.php"
".\kGen\kGEN.exe" "generate-interfaces.SDR.json" > "..\Contracts\SDR-Contract\v1\interfaces.php"
".\kGen\kGEN.exe" "generate-interfaces.SMS.json" > "..\Contracts\SMS-Contract\v1\interfaces.php"
".\kGen\kGEN.exe" "generate-interfaces.VDR.json" > "..\Contracts\VDR-Contract\v1\interfaces.php"
".\kGen\kGEN.exe" "generate-interfaces.WDR.json" > "..\Contracts\WDR-Contract\v1\interfaces.php"

".\kGen\kGEN.exe" "generate-models.BDR.json" > "..\Contracts\BDR-Contract\v1\models.php"
".\kGen\kGEN.exe" "generate-models.IMS.json" > "..\Contracts\IMS-Contract\v1\models.php"
".\kGen\kGEN.exe" "generate-models.SDR.json" > "..\Contracts\SDR-Contract\v1\models.php"
".\kGen\kGEN.exe" "generate-models.SMS.json" > "..\Contracts\SMS-Contract\v1\models.php"
".\kGen\kGEN.exe" "generate-models.VDR.json" > "..\Contracts\VDR-Contract\v1\models.php"
".\kGen\kGEN.exe" "generate-models.WDR.json" > "..\Contracts\WDR-Contract\v1\models.php"

".\kGen\kGEN.exe" "generate-wrappers.BDR.json" > "..\Contracts\BDR-Contract\v1\dtos.php"
".\kGen\kGEN.exe" "generate-wrappers.IMS.json" > "..\Contracts\IMS-Contract\v1\dtos.php"
".\kGen\kGEN.exe" "generate-wrappers.SDR.json" > "..\Contracts\SDR-Contract\v1\dtos.php"
".\kGen\kGEN.exe" "generate-wrappers.SMS.json" > "..\Contracts\SMS-Contract\v1\dtos.php"
".\kGen\kGEN.exe" "generate-wrappers.VDR.json" > "..\Contracts\VDR-Contract\v1\dtos.php"
".\kGen\kGEN.exe" "generate-wrappers.WDR.json" > "..\Contracts\WDR-Contract\v1\dtos.php"
