<?php
/* based on ORSCF StudyManagement Contract v1.6.0.0 */

use \MedicalResearch\StudyManagement\Model;

namespace MedicalResearch\StudyManagement\StoreAccess {
  
  public class Institute {
    
    /*
    * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    */
    public $instituteUid;
    
    /*
    * An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record. *this field has a max length of 100
    */
    public $displayLabel;
    
    public $isArchived;
    
    public $ownPatientSdrEndpointUid;
    
  }
  
  public class InstituteRelatedSystemAssignemnt {
    
    public $instituteRelatedSystemAssignemntUid;
    
    public $systemEndpointUid;
    
    public $instituteUid;
    
    public $useAsOwnPatientSdr;
    
    public $useAsCandidateSdr;
    
    public $useAsOwnWdr;
    
    public $useAsConsumingExternalWdr;
    
  }
  
  public class InvolvedPerson {
    
    /*
    * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    */
    public $involvedPersonUid;
    
    /*
    * *this field is optional (use null as value)
    */
    public $displayLabel;
    
    /*
    * *this field is optional
    */
    public $emailAddress;
    
    public $isArchived;
    
  }
  
  public class InvolvementRole {
    
    /*
    * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    */
    public $involvedPersonRoleUid;
    
    public $researchStudyUid;
    
    /*
    * *this field is optional (use null as value)
    */
    public $role;
    
    /*
    * *this field is optional
    */
    public $involvedFrom;
    
    /*
    * *this field is optional
    */
    public $involvedUntil;
    
    /*
    * null indicated a site independent global role *this field is optional
    */
    public $dedicatedToSiteUid;
    
    public $involvedPersonUid;
    
  }
  
  /*
  * entity, which relates to <see href="https://www.hl7.org/fhir/researchstudy.html">HL7.ResearchStudy</see>
  */
  public class ResearchStudy {
    
    /*
    * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    */
    public $researchStudyUid;
    
    /*
    * An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record. *this field has a max length of 100
    */
    public $displayLabel;
    
    public $initiatorInstituteUid;
    
    public $studyWorkflowName;
    
    public $studyWorkflowVersion;
    
    /*
    * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-study-phase.html">HL7.ResearchStudyPhase</see>: n-a | early-phase-1 | phase-1 | phase-1-phase-2 | phase-2 | phase-2-phase-3 | phase-3 | phase-4 *this field is optional (use null as value)
    */
    public $phase;
    
    /*
    * a estimated date in future is possible *this field is optional
    */
    public $startDate;
    
    /*
    * a estimated date in future is possible *this field is optional
    */
    public $terminationDate;
    
    /*
    * A title which informs about the sematic of the SubjectIdentifer (which concrete value is used): "Randomization-Number", "Screening-Number", ...
    */
    public $subjectIdentifierTitle;
    
    /*
    * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-study-status.html">HL7.ResearchStudyStatus</see>: active | administratively-completed | approved | closed-to-accrual | closed-to-accrual-and-intervention | completed | disapproved | in-review | temporarily-closed-to-accrual | temporarily-closed-to-accrual-and-intervention | withdrawn
    */
    public $status;
    
    /*
    * *this field is optional (use null as value)
    */
    public $terminatedReason;
    
    public $isArchived;
    
    /*
    * *this field is optional (use null as value)
    */
    public $initiatorRelatedProjectNumber;
    
    public $originWdrEndpointUid;
    
    public $primaryImsEndpointUid;
    
  }
  
  public class Site {
    
    /*
    * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    */
    public $siteUid;
    
    /*
    * <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> of the institute, which is representing this site
    */
    public $representingInstituteUid;
    
    /*
    * <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> of the related record
    */
    public $researchStudyUid;
    
    /*
    * a estimated date in future is possible *this field is optional
    */
    public $enrollmentDate;
    
    /*
    * a estimated date in future is possible *this field is optional
    */
    public $terminationDate;
    
    /*
    * *this field is optional (use null as value)
    */
    public $terminatedReason;
    
    /*
    * Offical 'SiteIdentifier' which is unique within the scope of the related study
    */
    public $studyRelatedSiteIdentifer;
    
    /*
    * An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record.
    */
    public $displayLabel;
    
    /*
    * AS DECLARED BY HL7
    */
    public $status;
    
    /*
    * *this field is optional (use null as value)
    */
    public $siteRelatedProjectNumber;
    
  }
  
  public class SiteRelatedSystemAssignment {
    
    public $siteRelatedSystemAssignmentUid;
    
    public $systemEndpointUid;
    
    public $siteUid;
    
  }
  
  public class StudyRelatedSystemAssignment {
    
    public $studyRelatedSystemAssignmentUid;
    
    public $researchStudyUid;
    
    public $systemEndpointUid;
    
  }
  
  public class SystemConnection {
    
    public $systemConnectionUid;
    
    public $ownerInstituteUid;
    
    public $hierSpäterJWTSEttings;
    
    public $targetSystemEndpointUid;
    
    /*
    * *this field is optional
    */
    public $dedicatedSiteRelatedSystemAssignmentUid;
    
  }
  
  public class SystemEndpoint {
    
    public $systemEndpointUid;
    
    public $providerInstituteUid;
    
    public $availableRoles;
    
    public $url;
    
    public $approvedCert;
    
    public $isPublic;
    
    public $label;
    
  }
  
}
