<?php
/* based on ORSCF SubjectData Contract v1.9.1.11852 */


public class UidValueCriteria {
  
  /*
  * The value to match.
  */
  public string $value;
  
}

public class StringValueCriteria {
  
  /*
  * The value to match.
  */
  public string $value;
  
  /*
  * Enables, that the given value can just be a substring within the content of the target field. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $matchSubstring;
  
}

/*
* Declares, how the corresponding 'value' should be compared. DEFAULT (if this is undefined or null) is 'Equal'(1).
*/
public interface RangeMatchingBehaviour extends Enum {
  
}

public class SubjectMetaRecord {
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $subjectUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $studyUid;
  
  public string $actualSiteUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class CustomFieldDescriptor {
  
  public string $technicalName;
  
  public bool $isRequired;
  
  public string $displayLabel;
  
  public string $inputDescription;
  
  public string $defaultValue;
  
  public array $presets;
  
  public bool $presetsOnly;
  
  public string $regularExpression;
  
}

public class SubjectFields implements SubjectMetaRecord {
  
  public string $enrollingSiteUid;
  
  /*
  * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
  */
  public string $status;
  
  /*
  * a note (manually written text) which provides some additional information about the reason why one transitioned to the current status
  */
  public string $statusNote;
  
  public string $periodStart;
  
  public string $periodEnd;
  
  public string $assignedArm;
  
  public string $actualArm;
  
  public array $substudyNames;
  
  /*
  * This can be the ID ('surrogate-key') of the Partient record within a site specific patient management system. This MUST NOT be any natural key or plain readable name which exposes the identity of the patient!
  */
  public string $actualSiteDefinedPatientIdentifier;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $subjectUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $studyUid;
  
  public string $actualSiteUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class SubjectStructure implements SubjectFields {
  
  public string $enrollingSiteUid;
  
  /*
  * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
  */
  public string $status;
  
  /*
  * a note (manually written text) which provides some additional information about the reason why one transitioned to the current status
  */
  public string $statusNote;
  
  public string $periodStart;
  
  public string $periodEnd;
  
  public string $assignedArm;
  
  public string $actualArm;
  
  public array $substudyNames;
  
  /*
  * This can be the ID ('surrogate-key') of the Partient record within a site specific patient management system. This MUST NOT be any natural key or plain readable name which exposes the identity of the patient!
  */
  public string $actualSiteDefinedPatientIdentifier;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $subjectUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $studyUid;
  
  public string $actualSiteUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

/*
* A structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
*/
public class SubjectFhirRessourceContainer implements SubjectMetaRecord {
  
  /*
  * a HL7 <see href="https://www.hl7.org/fhir/researchsubject.html">'ResearchSubject'</see> resource in json format
  */
  public object $researchSubjectRessource;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $subjectUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $studyUid;
  
  public string $actualSiteUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class BatchableSubjectMutation {
  
  /*
  * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
  */
  public string $status;
  
  public string $assignedArm;
  
  public string $actualArm;
  
  public ?string $periodStart;
  
  public ?string $periodEnd;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
}

public class UidFieldFilter {
  
  /*
  * Specifies one or more values to match. DEFAULT (if this is undefined or null) will include everything (but NULL) to enable filtering based on 'excluded values'. An empty array which just has no elements will be treaded as valid input and results in no value matching, so this only makes sense when including NULL instead (if supported). An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $includedValues;
  
  /*
  * Specifies one or more values to be removed from the result set which was evaulated using the 'included values'. DEFAULT (if this is undefined or null) will just leave the filtering based on 'included values'. An empty array which just has no elements will also be ignored. An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $excludedValues;
  
  /*
  * Negates the outcome of the whole filter. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $negate;
  
}

public class StringFieldFilter {
  
  /*
  * Specifies one or more values to match. DEFAULT (if this is undefined or null) will include everything (but NULL) to enable filtering based on 'excluded values'. An empty array which just has no elements will be treaded as valid input and results in no value matching, so this only makes sense when including NULL instead (if supported). An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $includedValues;
  
  /*
  * Specifies one or more values to be removed from the result set which was evaulated using the 'included values'. DEFAULT (if this is undefined or null) will just leave the filtering based on 'included values'. An empty array which just has no elements will also be ignored. An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $excludedValues;
  
  /*
  * Enables, that the included and excluded values are processed case-insenstive. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $ignoreCasing;
  
  /*
  * Negates the outcome of the whole filter. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $negate;
  
}

public class DateValueCriteria {
  
  /*
  * The value to match.
  */
  public string $value;
  
  /*
  * Declares, how the corresponding 'value' should be compared. DEFAULT (if this is undefined or null) is 'Equal'(1).
  */
  public RangeMatchingBehaviour $matchingBehaviour;
  
}

public class DateFieldFilter {
  
  /*
  * Specifies one or more values to match. DEFAULT (if this is undefined or null) will include everything (but NULL) to enable filtering based on 'excluded values'. An empty array which just has no elements will be treaded as valid input and results in no value matching, so this only makes sense when including NULL instead (if supported). An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $includedValues;
  
  /*
  * Specifies one or more values to be removed from the result set which was evaulated using the 'included values'. DEFAULT (if this is undefined or null) will just leave the filtering based on 'included values'. An empty array which just has no elements will also be ignored. An array containing multiple elements, will require at least ONE of the criteria to match (OR-linked)!
  */
  public array $excludedValues;
  
  /*
  * Negates the outcome of the whole filter. DEFAULT (if this is undefined or null) is 'false'.
  */
  public bool $negate;
  
}

public class SubjectFilter {
  
  public UidFieldFilter $studyUid;
  
  public UidFieldFilter $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public StringFieldFilter $subjectIdentifier;
  
  /*
  * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
  */
  public StringFieldFilter $status;
  
  public DateFieldFilter $periodStart;
  
  public DateFieldFilter $periodEnd;
  
  public StringFieldFilter $assignedArm;
  
  public StringFieldFilter $actualArm;
  
  public StringFieldFilter $substudyName;
  
  /*
  * This can be the ID ('surrogate-key') of the Partient record within a site specific patient management system. This MUST NOT be any natural key or plain readable name which exposes the identity of the patient!
  */
  public StringFieldFilter $actualSiteDefinedPatientIdentifier;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
}
