<?php
/* based on ORSCF SubjectData Contract v1.8.0.11813 */


public class SubjectFilter {
  
  public ?string $studyUid;
  
  public ?string $siteUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  /*
  * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
  */
  public string $status;
  
  public ?string $minPeriodStart;
  
  public ?string $maxPeriodStart;
  
  public ?string $minPeriodEnd;
  
  public ?string $maxPeriodEnd;
  
  public string $assignedArm;
  
  public string $actualArm;
  
  public string $substudyName;
  
  /*
  * This can be the ID ('surrogate-key') of the Partient record within a site specific patient management system. This MUST NOT be any natural key or plain readable name which exposes the identity of the patient!
  */
  public string $actualSiteDefinedPatientIdentifier;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
}

public class SubjectMetaRecord {
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $subjectUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $studyUid;
  
  public string $actualSiteUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class CustomFieldDescriptor {
  
  public string $technicalName;
  
  public bool $isRequired;
  
  public string $displayLabel;
  
  public string $inputDescription;
  
  public string $defaultValue;
  
  public array $presets;
  
  public bool $presetsOnly;
  
  public string $regularExpression;
  
}

public class SubjectFields implements SubjectMetaRecord {
  
  public string $enrollingSiteUid;
  
  /*
  * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
  */
  public string $status;
  
  /*
  * a note (manually written text) which provides some additional information about the reason why one transitioned to the current status
  */
  public string $statusNote;
  
  public string $periodStart;
  
  public string $periodEnd;
  
  public string $assignedArm;
  
  public string $actualArm;
  
  public array $substudyNames;
  
  /*
  * This can be the ID ('surrogate-key') of the Partient record within a site specific patient management system. This MUST NOT be any natural key or plain readable name which exposes the identity of the patient!
  */
  public string $actualSiteDefinedPatientIdentifier;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $subjectUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $studyUid;
  
  public string $actualSiteUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class SubjectStructure implements SubjectFields {
  
  public string $enrollingSiteUid;
  
  /*
  * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
  */
  public string $status;
  
  /*
  * a note (manually written text) which provides some additional information about the reason why one transitioned to the current status
  */
  public string $statusNote;
  
  public string $periodStart;
  
  public string $periodEnd;
  
  public string $assignedArm;
  
  public string $actualArm;
  
  public array $substudyNames;
  
  /*
  * This can be the ID ('surrogate-key') of the Partient record within a site specific patient management system. This MUST NOT be any natural key or plain readable name which exposes the identity of the patient!
  */
  public string $actualSiteDefinedPatientIdentifier;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $subjectUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $studyUid;
  
  public string $actualSiteUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

/*
* A structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
*/
public class SubjectFhirRessourceContainer implements SubjectMetaRecord {
  
  /*
  * a HL7 <see href="https://www.hl7.org/fhir/researchsubject.html">'ResearchSubject'</see> resource in json format
  */
  public object $researchSubjectRessource;
  
  /*
  * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
  */
  public string $subjectUid;
  
  /*
  * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
  */
  public string $subjectIdentifier;
  
  public string $studyUid;
  
  public string $actualSiteUid;
  
  /*
  * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
  */
  public bool $isArchived;
  
  /*
  * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
  */
  public int $modificationTimestampUtc;
  
}

public class BatchableSubjectMutation {
  
  /*
  * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
  */
  public string $status;
  
  public string $assignedArm;
  
  public string $actualArm;
  
  public ?string $periodStart;
  
  public ?string $periodEnd;
  
  /*
  * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
  */
  public object $customFields;
  
}
